apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo02-deployment
  labels:
    app: acrdemo02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo02
  template:
    metadata:
      labels:
        app: acrdemo02
    spec:
      containers:
        - name: acrdemo02 
          image: acrdemo02.azurecr.io/app2/acr-app2:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acrdemo02-secret  
