apiVersion: v1
kind: Service
metadata:
  name: acrdemo02-loadbalancer-service
  labels:
    app: acrdemo02
spec:
  type: LoadBalancer
  selector:
    app: acrdemo02
  ports:
    - port: 80
      targetPort: 80
